---
# yamllint disable rule:line-length
apiVersion: industry-fusion.com/v1alpha4
kind: BeamSqlStatementSet
metadata:
    name: core-services
    annotations:
        checksum/config: >-
            {{ include (print $.Template.BasePath "/core-tables.yaml") . | sha256sum }}
            {{ include (print $.Template.BasePath "/core-kafka-topics.yaml") . | sha256sum }}
spec:
    sqlsettings:
        - pipeline.object-reuse: 'true'
    sqlstatements:
        - |-
          /* validates changes in alerts_bulk and only forward if there are specific changes*/
            insert into alerts
            WITH WindowedAlerts AS (
                SELECT
                    `resource`,
                    `event`,
                    `environment`,
                    `service`,
                    `customer`,
                    LAST_VALUE(severity) AS `severity`,
                    LAST_VALUE(`text`) AS `text`,
                    TUMBLE_START(`ts`, INTERVAL {{.Values.flink.alertWindow | squote}} SECOND) AS window_start,
                    TUMBLE_END(`ts`, INTERVAL {{.Values.flink.alertWindow | squote}} SECOND) AS window_end,
                    TUMBLE_ROWTIME(`ts`, INTERVAL {{.Values.flink.alertWindow | squote}} SECOND) AS window_time
                FROM TABLE(
                    TUMBLE(TABLE alerts_bulk, DESCRIPTOR(ts), INTERVAL {{.Values.flink.alertWindow | squote}} SECOND)
                )
                GROUP BY
                    `resource`,
                    `event`,
                    `service`,
                    `customer`,
                    `environment`,
                    TUMBLE(`ts`, INTERVAL {{.Values.flink.alertWindow | squote}} SECOND)
            ),
            AlertsWithPreviousSeverity AS (
                SELECT
                    `resource`,
                    `event`,
                    `environment`,
                    `service`,
                    `customer`,
                    `severity`,
                    `text`,
                    `window_end`,
                    `window_time`,
                    LAG(`severity`) OVER (
                        PARTITION BY `resource`, `event`, `service`, `customer`, `environment`
                        ORDER BY `window_time`
                    ) AS prev_severity
                FROM WindowedAlerts
            )
            SELECT
                `resource`,
                `event`,
                `environment`,
                `service`,
                `severity`,
                `customer`,
                `text`
            FROM
                AlertsWithPreviousSeverity
            WHERE
                prev_severity IS NULL OR severity <> prev_severity;
        - |-
            /* aggregates entities from attributes topic and insert it every 2 seconds in update channel
            part of CORE SERVICES */
            insert into ngsild_updates
                select 'update', true, true, '[{"id": "' || id || '",' || LISTAGG(attributeagg) || '}]'
                from (
                    select  window_start, window_end, B.entityId as id, '"' || B.name || '":[' || LISTAGG(B.indexagg) || ']' as attributeagg
                    from(
                        select window_start, window_end, entityId, name, `https://uri.etsi.org/ngsi-ld/datasetId`,
                        '{"observedAt": "' || LAST_VALUE(DATE_FORMAT(A.`ts`,  'yyyy-MM-dd''T''HH:mm:ss.') || CAST(EXTRACT(MILLISECOND from A.`ts`) as STRING)) || 'Z", "type": "'
                                || LAST_VALUE(A.`type`)
                                || '", "datasetId": "'
                                || IF(A.`https://uri.etsi.org/ngsi-ld/datasetId` IS NOT NULL, A.`https://uri.etsi.org/ngsi-ld/datasetId`, '@none')
                                || IF(LAST_VALUE(A.`type`) =  'https://uri.etsi.org/ngsi-ld/Relationship','", "object": "', '", "value": ')
                                || IF(LAST_VALUE(A.`type`) =  'https://uri.etsi.org/ngsi-ld/Relationship', LAST_VALUE(A.`https://uri.etsi.org/ngsi-ld/hasObject`) || '"',
                                        
                                        IF((LAST_VALUE(A.nodeType) <> '@json' AND LAST_VALUE(A.nodeType) <> '@id') OR LAST_VALUE(A.nodeType) IS NULL, '"' || LAST_VALUE(A.`https://uri.etsi.org/ngsi-ld/hasValue`) || '"',
                                            /* @id needs encoding with "@id": value */
                                            IF(LAST_VALUE(A.nodeType) = '@id', '{"@id": "' || LAST_VALUE(A.`https://uri.etsi.org/ngsi-ld/hasValue`) || '"}',
                                            /* @json is put directly into value field */
                                                IF(LAST_VALUE(A.nodeType) = '@json', LAST_VALUE(A.`https://uri.etsi.org/ngsi-ld/hasValue`), 'null' /*should not happen */)))
                                )
                                || '}' as indexagg
                        FROM TABLE( TUMBLE(TABLE attributes, DESCRIPTOR(ts), INTERVAL {{.Values.flink.ngsildUpdateWindow|squote}} second)) as A
                        WHERE A.entityId IS NOT NULL and (A.deleted IS NULL or A.deleted = false) and (A.synched IS NULL or A.synched = false)
                        GROUP BY A.entityId, A.name, A.`https://uri.etsi.org/ngsi-ld/datasetId`, window_start, window_end) as B
                    GROUP BY window_start, window_end, entityId, name, `https://uri.etsi.org/ngsi-ld/datasetId`
                ) GROUP BY window_start, window_end, id;
        - |-
            /* forward only non-retracted attribute changes
            This is part of the core service */
            insert into attributes_writeback
            select entityId, name, nodeType, valueType, `type`, `https://uri.etsi.org/ngsi-ld/datasetId`, `https://uri.etsi.org/ngsi-ld/hasValue`, `https://uri.etsi.org/ngsi-ld/hasObject` from
            (select entityId as entityId, name as name, last_value(nodeType) as nodeType, last_value(valueType) as valueType , last_value(`type`) as `type`,
            `https://uri.etsi.org/ngsi-ld/datasetId` as `https://uri.etsi.org/ngsi-ld/datasetId`,
            last_value(`https://uri.etsi.org/ngsi-ld/hasValue`) as `https://uri.etsi.org/ngsi-ld/hasValue`,
            last_value(`https://uri.etsi.org/ngsi-ld/hasObject`) as `https://uri.etsi.org/ngsi-ld/hasObject`,
              TUMBLE_START(ts, INTERVAL {{ .Values.flink.attributeInsertWindow |squote }} SECOND),
              TUMBLE_END(ts, INTERVAL {{ .Values.flink.attributeInsertWindow |squote }} SECOND)
            from attributes_insert
            group by entityId, name, `https://uri.etsi.org/ngsi-ld/datasetId`, TUMBLE(ts, INTERVAL {{ .Values.flink.attributeInsertWindow |squote }} SECOND));

    tables:
        - alerts
        - alerts-bulk
        - attributes
        - attributes-writeback
        - attributes-insert
        - attributes-insert-filter
        - ngsild-updates
    views:
        - attributes-insert-view