---
{{- $topicExists := (lookup "kafka.strimzi.io/v1beta2" "KafkaTopic" .Release.Namespace .Values.kafkaBridge.alerta.bulkTopic) }}
{{- if not $topicExists }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafkaBridge.alerta.bulkTopic}}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{.Values.kafkaBridge.alerta.bulkTopicRetention}}
{{- end }}
---
{{- $topicExists := (lookup "kafka.strimzi.io/v1beta2" "KafkaTopic" .Release.Namespace .Values.kafkaBridge.alerta.listenTopic) }}
{{- if not $topicExists }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafkaBridge.alerta.listenTopic}}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{.Values.kafkaBridge.alerta.listenTopicRetention}}
{{- end }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafkaBridge.ngsildUpdates.listenTopic}}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{.Values.kafkaBridge.ngsildUpdates.listenTopicRetention}}
---
{{- $topicExists := (lookup "kafka.strimzi.io/v1beta2" "KafkaTopic" .Release.Namespace .Values.kafkaBridge.debezium.attributesTopic) }}
{{- if not $topicExists }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.kafkaBridge.debezium.attributesTopic }}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{ .Values.kafkaBridge.debezium.attributesTopicRetention }}
    compression.type: {{ .Values.kafkaBridge.debezium.attributesTopicCompression }}
{{- end }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafkaBridge.debezium.attributesTopic}}-insert
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: '{{.Values.kafkaBridge.alerta.bulkTopicRetention}}'
  topicName: {{.Values.kafkaBridge.debezium.attributesTopic}}_insert
