//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompositionSelector) DeepCopyInto(out *CompositionSelector) {
	*out = *in
	out.MatchLabels = in.MatchLabels
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompositionSelector.
func (in *CompositionSelector) DeepCopy() *CompositionSelector {
	if in == nil {
		return nil
	}
	out := new(CompositionSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DigitalTwinPlatform) DeepCopyInto(out *DigitalTwinPlatform) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DigitalTwinPlatform.
func (in *DigitalTwinPlatform) DeepCopy() *DigitalTwinPlatform {
	if in == nil {
		return nil
	}
	out := new(DigitalTwinPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DigitalTwinPlatform) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DigitalTwinPlatformList) DeepCopyInto(out *DigitalTwinPlatformList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DigitalTwinPlatform, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DigitalTwinPlatformList.
func (in *DigitalTwinPlatformList) DeepCopy() *DigitalTwinPlatformList {
	if in == nil {
		return nil
	}
	out := new(DigitalTwinPlatformList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DigitalTwinPlatformList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DigitalTwinPlatformSpec) DeepCopyInto(out *DigitalTwinPlatformSpec) {
	*out = *in
	out.Parameters = in.Parameters
	out.CompositionSelector = in.CompositionSelector
	out.WriteConnectionSecretToRef = in.WriteConnectionSecretToRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DigitalTwinPlatformSpec.
func (in *DigitalTwinPlatformSpec) DeepCopy() *DigitalTwinPlatformSpec {
	if in == nil {
		return nil
	}
	out := new(DigitalTwinPlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DigitalTwinPlatformStatus) DeepCopyInto(out *DigitalTwinPlatformStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DigitalTwinPlatformStatus.
func (in *DigitalTwinPlatformStatus) DeepCopy() *DigitalTwinPlatformStatus {
	if in == nil {
		return nil
	}
	out := new(DigitalTwinPlatformStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchLabels) DeepCopyInto(out *MatchLabels) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchLabels.
func (in *MatchLabels) DeepCopy() *MatchLabels {
	if in == nil {
		return nil
	}
	out := new(MatchLabels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parameters) DeepCopyInto(out *Parameters) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parameters.
func (in *Parameters) DeepCopy() *Parameters {
	if in == nil {
		return nil
	}
	out := new(Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WriteConnectionSecretToRef) DeepCopyInto(out *WriteConnectionSecretToRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WriteConnectionSecretToRef.
func (in *WriteConnectionSecretToRef) DeepCopy() *WriteConnectionSecretToRef {
	if in == nil {
		return nil
	}
	out := new(WriteConnectionSecretToRef)
	in.DeepCopyInto(out)
	return out
}
