---
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "minio-user") -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-bucket
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-minio
        image: busybox:1.28
        command: ['sh', '-c', "until wget -S {{ printf "%s://%s" .Values.s3.protocol .Values.s3.endpoint }}{{ .Values.minio.healthPath }} 2>&1 | awk '/^  HTTP/{print $2}' | grep 200; do echo waiting for minio; sleep 1; done"]
      containers:
      - name: create-bucket
        image: {{ .Values.minio.mcImage }}
        env:
        - name: MC_HOST_iff
          {{ if $secret}}
          value: {{ printf "%s://%s:%s@%s" .Values.s3.protocol .Values.s3.userAccessKey ($secret.data.CONSOLE_SECRET_KEY | b64dec) .Values.s3.endpoint }}
          {{ else }}
          value: {{ printf "%s://%s:%s@%s" .Values.s3.protocol .Values.s3.userAccessKey .Values.s3.userSecretKey .Values.s3.endpoint }}
          {{ end }}
        command: ["/bin/bash", "-c", "echo $MC_HOST_IFF; mc mb -p iff/{{ .Values.db.backupBucket }}"]
      restartPolicy: Never
  backoffLimit: 4