---
{{- $name := printf "%s.%s.%s" .Values.db.dbUser .Values.clusterSvcName .Values.db.secretPostfix }}
{{- $shortname := printf "%s.%s.credentials" .Values.db.dbUser .Values.clusterSvcName }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $name) }}
{{- $shortsecret := (lookup "v1" "Secret" .Release.Namespace $shortname) }}
{{- if and $shortsecret (not $secret) }}
{{- $secret = $shortsecret}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.db.dbUser | b64enc }}
  {{- if $secret }}
  password: {{ $secret.data.password }}
  {{- else }}
  password: {{ .Values.dbpassword | toString | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $shortname }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.db.dbUser | b64enc }}
  {{- if $secret }}
  password: {{ $secret.data.password }}
  {{- else }}
  password: {{ .Values.dbpassword | toString | b64enc }}
  {{- end }}
---

{{- $name := printf "%s.%s.%s" .Values.db.dbReaderUser .Values.clusterSvcName .Values.db.secretPostfix }}
{{- $shortname := printf "%s.%s.credentials" .Values.db.dbReaderUser .Values.clusterSvcName }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $name) }}
{{- $shortsecret := (lookup "v1" "Secret" .Release.Namespace $shortname) }}
{{- if and $shortsecret (not $secret) }}
{{- $secret = $shortsecret}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.db.dbReaderUser | b64enc }}
  {{- if $secret }}
  password: {{ $secret.data.password }}
  {{- else }}
  password: {{ .Values.dbReaderPassword | toString | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $shortname }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.db.dbReaderUser | b64enc }}
  {{- if $secret }}
  password: {{ $secret.data.password }}
  {{- else }}
  password: {{ .Values.dbReaderPassword | toString | b64enc }}
  {{- end }}
---