## environment variables for keycloak
keycloak_crd:
  apiVersion: apiextensions.k8s.io/v1
  group: keycloak.org

keycloak_roles:
  apiVersion: rbac.authorization.k8s.io/v1
  apiGroup: rbac.authorization.k8s.io

  ################################### keycloakrealms_crd deployment #######################################################################
keycloakrealms_crd:
## Enable the keycloakrealms_crd deployment
  enabled: true 
  name: keycloakrealmimports.k8s.keycloak.org
  versions: v2alpha1
  scope: Namespaced
  storage: true
  served: true

  ################################### keycloaks_crd deployment #######################################################################
keycloaks_crd:
## Enable the keycloaks_crd deployment
  enabled: true 
  name: keycloaks.k8s.keycloak.org
  versions: v2alpha1
  scope: Namespaced
  storage: true
  served: true

    ################################### role_binding deployment #######################################################################
role_binding:
## Enable the role_binding deployment
  enabled: true 
  name: keycloak-operator
  Subjects:
    name: keycloak-operator
  roleRef:
    name: keycloak-operator

    ################################### role deployment #######################################################################
role:
## Enable the role deployment
  enabled: true 
  name: keycloak-operator

    ################################### service_account deployment #######################################################################
service_account:
## Enable the service_account deployment
  enabled: true 
  apiVersion: v1
  name: keycloak-operator


    ################################### custom_resource service #######################################################################
custom_resource:
## Enable the custom_resource deployment & service
  enabled: true
  apiVersion: k8s.keycloak.org/v2alpha1
  name: keycloak
  instances: 1
  ingress:
    enabled: false
  credentials:
    ADMIN_PASSWORD:
    ADMIN_USERNAME:

ingress:
  enabled: true

    ################################### keycloak-db-secret #######################################################################
keycloak_db:
  enabled: true

