## Operator name 
name: postgres-operator

## Database cluster team and service names
## clusterSvcName must begin with "<teamId>-"
##
teamId: acid
clusterSvcName: acid-minimal-cluster
dbPassword: 

## Number of pod instances in the cluster
##
podInstances: 2

## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
##
imagePullPolicy: Always

## Security Context
##
securityContext:
  runAsUser: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

## Pod Resources
##
podResources:
  requests:
    cpu: 100m
    memory: 250Mi
  limits:
    cpu: 500m
    memory: 500Mi

## Size of the Persistent Volume
##
pvSize: 1Gi

## Database users
##
dbUsers:
  ngb: # dbowner: [permissions]; refer to spilo documentation for available permissions
  - createrole
  - createdb
  - replication
  dbreader:
  - login
  - noinherit
  - nocreatedb
  - nocreaterole
  - nosuperuser

## Databases; corresponding DB owner must be specified above
##
databases:
  ngb: ngb # dbname: dbowner
  keycloakdb: ngb # keycloak
  monitoring: ngb # alerta
  tsdb: ngb # timescaledb ngsild timeseries data

preparedTimescaleDatabases: tsdb
preparedPostgisDatabases: ngb