/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/IndustryFusion/DigitalTwin/platformkickstart/pkg/crd/digitaltwinplatform/v1alpha1"
	digitaltwinplatformv1alpha1 "github.com/IndustryFusion/DigitalTwin/platformkickstart/pkg/crd/digitaltwinplatform/v1alpha1/apis/applyconfiguration/digitaltwinplatform/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDigitalTwinPlatforms implements DigitalTwinPlatformInterface
type FakeDigitalTwinPlatforms struct {
	Fake *FakeCrossplaneV1alpha1
	ns   string
}

var digitaltwinplatformsResource = v1alpha1.SchemeGroupVersion.WithResource("digitaltwinplatforms")

var digitaltwinplatformsKind = v1alpha1.SchemeGroupVersion.WithKind("DigitalTwinPlatform")

// Get takes name of the digitalTwinPlatform, and returns the corresponding digitalTwinPlatform object, and an error if there is any.
func (c *FakeDigitalTwinPlatforms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DigitalTwinPlatform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(digitaltwinplatformsResource, c.ns, name), &v1alpha1.DigitalTwinPlatform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DigitalTwinPlatform), err
}

// List takes label and field selectors, and returns the list of DigitalTwinPlatforms that match those selectors.
func (c *FakeDigitalTwinPlatforms) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DigitalTwinPlatformList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(digitaltwinplatformsResource, digitaltwinplatformsKind, c.ns, opts), &v1alpha1.DigitalTwinPlatformList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DigitalTwinPlatformList{ListMeta: obj.(*v1alpha1.DigitalTwinPlatformList).ListMeta}
	for _, item := range obj.(*v1alpha1.DigitalTwinPlatformList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested digitalTwinPlatforms.
func (c *FakeDigitalTwinPlatforms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(digitaltwinplatformsResource, c.ns, opts))

}

// Create takes the representation of a digitalTwinPlatform and creates it.  Returns the server's representation of the digitalTwinPlatform, and an error, if there is any.
func (c *FakeDigitalTwinPlatforms) Create(ctx context.Context, digitalTwinPlatform *v1alpha1.DigitalTwinPlatform, opts v1.CreateOptions) (result *v1alpha1.DigitalTwinPlatform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(digitaltwinplatformsResource, c.ns, digitalTwinPlatform), &v1alpha1.DigitalTwinPlatform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DigitalTwinPlatform), err
}

// Update takes the representation of a digitalTwinPlatform and updates it. Returns the server's representation of the digitalTwinPlatform, and an error, if there is any.
func (c *FakeDigitalTwinPlatforms) Update(ctx context.Context, digitalTwinPlatform *v1alpha1.DigitalTwinPlatform, opts v1.UpdateOptions) (result *v1alpha1.DigitalTwinPlatform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(digitaltwinplatformsResource, c.ns, digitalTwinPlatform), &v1alpha1.DigitalTwinPlatform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DigitalTwinPlatform), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDigitalTwinPlatforms) UpdateStatus(ctx context.Context, digitalTwinPlatform *v1alpha1.DigitalTwinPlatform, opts v1.UpdateOptions) (*v1alpha1.DigitalTwinPlatform, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(digitaltwinplatformsResource, "status", c.ns, digitalTwinPlatform), &v1alpha1.DigitalTwinPlatform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DigitalTwinPlatform), err
}

// Delete takes name of the digitalTwinPlatform and deletes it. Returns an error if one occurs.
func (c *FakeDigitalTwinPlatforms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(digitaltwinplatformsResource, c.ns, name, opts), &v1alpha1.DigitalTwinPlatform{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDigitalTwinPlatforms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(digitaltwinplatformsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DigitalTwinPlatformList{})
	return err
}

// Patch applies the patch and returns the patched digitalTwinPlatform.
func (c *FakeDigitalTwinPlatforms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DigitalTwinPlatform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(digitaltwinplatformsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DigitalTwinPlatform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DigitalTwinPlatform), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied digitalTwinPlatform.
func (c *FakeDigitalTwinPlatforms) Apply(ctx context.Context, digitalTwinPlatform *digitaltwinplatformv1alpha1.DigitalTwinPlatformApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.DigitalTwinPlatform, err error) {
	if digitalTwinPlatform == nil {
		return nil, fmt.Errorf("digitalTwinPlatform provided to Apply must not be nil")
	}
	data, err := json.Marshal(digitalTwinPlatform)
	if err != nil {
		return nil, err
	}
	name := digitalTwinPlatform.Name
	if name == nil {
		return nil, fmt.Errorf("digitalTwinPlatform.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(digitaltwinplatformsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.DigitalTwinPlatform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DigitalTwinPlatform), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeDigitalTwinPlatforms) ApplyStatus(ctx context.Context, digitalTwinPlatform *digitaltwinplatformv1alpha1.DigitalTwinPlatformApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.DigitalTwinPlatform, err error) {
	if digitalTwinPlatform == nil {
		return nil, fmt.Errorf("digitalTwinPlatform provided to Apply must not be nil")
	}
	data, err := json.Marshal(digitalTwinPlatform)
	if err != nil {
		return nil, err
	}
	name := digitalTwinPlatform.Name
	if name == nil {
		return nil, fmt.Errorf("digitalTwinPlatform.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(digitaltwinplatformsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.DigitalTwinPlatform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DigitalTwinPlatform), err
}
