{{- $secret := "" }}
{{- if .Values.minio.enabled }}
  {{- $secret = (lookup "v1" "Secret" .Values.namespace "minio-user") -}}
{{- end }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: velero-s3-credentials
stringData:
  cloud: |
    [default]
    aws_access_key_id={{ .Values.s3.userAccessKey }}
    {{- if $secret }}
    aws_secret_access_key={{ ($secret.data.CONSOLE_SECRET_KEY | b64dec) }}
    {{- else }}
    aws_secret_access_key={{ .Values.s3.userSecretKey }}
    {{- end }}