---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: beamsqlstatementsets.industry-fusion.com
spec:
  scope: Namespaced
  group: industry-fusion.com
  versions:
    - name: v1alpha1
      served: true
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - sqlstatements
                - tables
              properties:
                sqlstatements:
                  type: array
                  items:
                    type: string
                tables:
                  type: array
                  items:
                    type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                state:
                  type: string
                job_id:
                  type: string
    - name: v1alpha2
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - sqlstatements
                - tables
              properties:
                sqlstatements:
                  type: array
                  items:
                    type: string
                tables:
                  type: array
                  items:
                    type: string
                views:
                  type: array
                  items:
                    type: string
                sqlsettings:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                updateStrategy:
                  type: string
                  enum: [
                    "none",
                    "savepoint"
                  ]
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                state:
                  type: string
                job_id:
                  type: string
    - name: v1alpha3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sqlstatements:
                  type: array
                  items:
                    type: string
                sqlstatementmaps:
                  type: array
                  items:
                    type: string
                tables:
                  type: array
                  items:
                    type: string
                views:
                  type: array
                  items:
                    type: string
                sqlsettings:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                updateStrategy:
                  type: string
                  enum: ["none", "savepoint"]
              required:
              - tables
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                state:
                  type: string
                job_id:
                  type: string
  names:
    kind: BeamSqlStatementSet
    plural: beamsqlstatementsets
    singular: beamsqlstatementset
    shortNames:
      - bsqls
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: beamsqltables.industry-fusion.com
spec:
  scope: Namespaced
  group: industry-fusion.com
  versions:
    - name: v1alpha1
      served: true
      storage: false
      deprecated: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - connector
                - fields
                - kafka
                - value
              properties:
                connector:
                  type: string
                  enum: [
                    "kafka",
                    "upsert-kafka"
                  ]
                fields:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                kafka:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                value:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                primaryKey:
                  type: array
                  items:
                    type: string
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - connector
                - fields
                - kafka
                - value
              properties:
                connector:
                  type: string
                  enum: [
                    "kafka",
                    "upsert-kafka"
                  ]
                fields:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                kafka:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                value:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                primaryKey:
                  type: array
                  items:
                    type: string
                name:
                  type: string
  names:
    kind: BeamSqlTable
    plural: beamsqltables
    singular: beamsqltable
    shortNames:
      - bsqlt
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: beamsqlviews.industry-fusion.com
spec:
  scope: Namespaced
  group: industry-fusion.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - sqlstatement
              properties:
                sqlstatement:
                  type: string
                name:
                  type: string
  names:
    kind: BeamSqlView
    plural: beamsqlviews
    singular: beamsqlview
    shortNames:
      - bsqlv
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flinkpythonudfs.industry-fusion.com
spec:
  scope: Namespaced
  group: industry-fusion.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - class
                - filename
                - version
              properties:
                class:
                  type: string
                filename:
                  type: string
                version:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                state:
                  type: string
  names:
    kind: flinkpythonudf
    plural: flinkpythonudfs
    singular: flinkpythonudf
    shortNames:
      - fpudf
