{{- $name := printf "%s.%s.%s" .Values.db.dbUser .Values.clusterSvcName .Values.db.secretPostfix -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $name) -}}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: {{ .Values.kafkaConnector.name }}
  labels:
    strimzi.io/cluster: {{ .Values.kafkaConnectConfig.name }}
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    snapshot.mode: {{ .Values.kafka.connect.snapshotMode }}
    database.hostname: {{ .Values.clusterSvcName | quote }}
    database.port: {{ .Values.db.svcPort | quote }}
    database.user: {{ .Values.db.dbUser | quote }}
    {{ if $secret }}
    database.password: {{ $secret.data.password | b64dec | quote }}
    {{ else }}
    database.password: "password not found in secrets"
    {{ end }}
    database.dbname: {{ .Values.db.scorpioDb | quote}}
    database.server.name: {{ .Values.kafka.connect.debeziumTopicPrefix | quote }}
    table.include.list: {{ .Values.kafka.connect.tableIncludeList | quote }}
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: "false"
    value.converter.schemas.enable: "false"