{{- $secret := (lookup "v1" "Secret" .Release.Namespace "minio-user") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/flink-configuration-configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.flink.jobmanagers }} # Set the value to greater than 1 to start standby JobManagers
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      initContainers:
      - name: wait-for-minio
        image: busybox:1.28
        command: ['sh', '-c', "until wget -S {{ .Values.minio.url }}{{ .Values.minio.healthPath }} 2>&1 | awk '/^  HTTP/{print $2}' | grep 200; do echo waiting for minio; sleep 1; done"]
      - name: create-bucket
        image: {{ .Values.minio.mcImage }}
        env:
        - name: MC_HOST_iff
          {{ if $secret}}
          value: {{ printf "http://%s:%s@%s" .Values.minio.userAccessKey ($secret.data.CONSOLE_SECRET_KEY | b64dec) .Values.minio.endpoint }}
          {{ else }}
          value: {{ printf "http://novalidkey" }}
          {{ end }}
        command: ["/bin/bash", "-c", "mc mb -p iff/{{ .Values.flink.bucket }}"]
      containers:
      - name: jobmanager
        image: apache/flink:{{ .Values.flink.imageTag }}
        workingDir: /opt/flink
        command: ["/bin/bash", "-c", "mkdir -p /opt/flink/plugins/s3; \
          cp /opt/flink/opt/flink-s3-fs-hadoop-*.jar /opt/flink/plugins/s3 ; \
          $FLINK_HOME/bin/jobmanager.sh start-foreground; \
          "]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        # The following args overwrite the value of jobmanager.rpc.address configured in the configuration config map to POD_IP.
        args: ["jobmanager", "$(POD_IP)"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob-server
        - containerPort: 8081
          name: webui
        livenessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        securityContext:
          runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary
      - name: sql-gateway
        image: {{ .Values.mainRepo }}/flink-sql-gateway:{{ .Values.mainVersion }}
        workingDir: /opt/gateway
        command: ["/bin/bash", "-c", "mkdir -p /opt/flink/plugins/s3; \
          cp /opt/flink/opt/flink-s3-fs-hadoop-*.jar /opt/flink/plugins/s3 ; \
          ${NODEJSPATH}/node gateway.js"]
        env:
        - name: SIMPLE_FLINK_SQL_GATEWAY_PORT
          value: {{ .Values.flink.sqlClientPort | quote }}
        ports:
        - containerPort: {{ .Values.flink.sqlClientPort }}
          name: rest
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.flink.sqlClientPort }}
          initialDelaySeconds: 30
          periodSeconds: 3
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        securityContext:
          runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary

      serviceAccountName: flink-service-account # Service account which has the permissions to create, edit, delete ConfigMaps
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j-console.properties
            path: log4j-console.properties
      imagePullSecrets:
        - name: {{ .Values.pullSecretCredentials }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-service-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flink-service-account
rules:
 - apiGroups: [""] # "" indicates the core API group
   resources: ["configmaps"]
   verbs: ["create", "edit", "delete", "watch", "get", "list", "patch", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flink-service-account
subjects:
  - kind: ServiceAccount
    name: flink-service-account
roleRef:
  kind: Role
  name: flink-service-account
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  - name: sql-gateway
    port: 9000
  selector:
    app: flink
    component: jobmanager
