apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-rest
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app: flink
    component: jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: flink-sql-gateway
spec:
  type: ClusterIP
  ports:
  - name: rest
    port: {{ .Values.flink.sqlClientPort }}
    targetPort: {{ .Values.flink.sqlClientPort }}
  selector:
    app: flink
    component: jobmanager