{{- $secret := (lookup "v1" "Secret" .Release.Namespace "keycloak-client-secret-fusion-backend") -}}
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-client-secret-fusion-backend
    namespace: {{ .Release.Namespace }}
    labels:
        velero-backup: "true"
{{ if $secret }}
data:
    CLIENT_ID: {{ $secret.data.CLIENT_ID }}
    CLIENT_SECRET: {{ $secret.data.CLIENT_SECRET }}
{{ else }}
data:
    CLIENT_ID: {{ .Values.keycloak.oisp.mqttBroker.client | toString | b64enc }}
    CLIENT_SECRET: {{ .Values.keycloak.oisp.mqttBroker.clientSecret | toString | b64enc }}
{{ end }}
type: Opaque