---
{{- if and (ne .Values.ingressType "traefik") (ne .Values.ingressType "nginx") }}
{{- fail "ingressType must either be \"traefik\" or \"nginx\"" }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-iff-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressType | quote }}
    cert-manager.io/cluster-issuer: {{ .Values.certmanager.issuer }}
  namespace: {{ .Release.Namespace }}
spec:
  tls:
  - hosts:
    - {{ .Values.keycloak.externalAuthService.domainname }}
    secretName: {{ .Values.certmanager.secret }}-keycloak
  rules:
  - host: {{ .Values.keycloak.externalAuthService.domainname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.keycloak.internalAuthService.name }}
            port:
              number: {{ .Values.keycloak.internalAuthService.port }}
        path: /
        pathType: ImplementationSpecific
---