{{- $secret := (lookup "v1" "Secret" .Release.Namespace "keycloak-initial-admin") -}}
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-initial-admin
    namespace: {{ .Release.Namespace }}
    labels:
        velero-backup: "true"
data:
    {{- if $secret }}
    password: {{ $secret.data.password }}
    {{- else }}
    password: {{ .Values.keycloak.adminPassword | toString | b64enc }}
    {{- end }}
    username: {{ .Values.keycloak.adminName | toString | b64enc }}
type: Opaque