{{- $secret := (lookup "v1" "Secret" .Release.Namespace "credential-keycloak") -}}
apiVersion: v1
kind: Secret
metadata:
    name: credential-keycloak
    namespace: {{ .Release.Namespace }}
data:
    {{- if $secret }}
    ADMIN_PASSWORD: {{ $secret.data.ADMIN_PASSWORD }}
    {{- else }}
    ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | toString | b64enc }}
    {{- end }}
    ADMIN_USERNAME: {{ .Values.keycloak.adminName | toString | b64enc }}
type: Opaque