{{- $pgsecretname := printf "%s.%s.%s" .Values.db.dbUser .Values.clusterSvcName .Values.db.secretPostfix -}}
{{- $pgsecret := (lookup "v1" "Secret" .Release.Namespace $pgsecretname) -}}
{{/*{{- $secret := (lookup "v1" "Secret" .Release.Namespace "keycloak-db-secret") -}} */}}
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: {{ .Release.Namespace }}
stringData:
    POSTGRES_DATABASE: {{ quote .Values.keycloak_db.stringData.POSTGRES_DATABASE  }}
    POSTGRES_EXTERNAL_ADDRESS: {{ quote .Values.clusterExternalSvcName }}
    POSTGRES_ADDR: {{ quote .Values.clusterExternalSvcName }}
    POSTGRES_EXTERNAL_PORT: {{ quote .Values.keycloak_db.stringData.POSTGRES_EXTERNAL_PORT }}
    # Required for AWS Backup functionality
    POSTGRES_SUPERUSER: {{ quote .Values.keycloak_db.stringData.POSTGRES_SUPERUSER }}
    POSTGRES_USERNAME: {{ quote .Values.keycloak_db.stringData.POSTGRES_USERNAME }}
data:
    {{ if $pgsecret }}
    POSTGRES_PASSWORD: {{ $pgsecret.data.password }}
    {{ else }} {{/* {{ if $secret }}
    POSTGRES_PASSWORD: {{ $secret.data.POSTGRES_PASSWORD }}
    {{ else }}
    POSTGRES_PASSWORD: {{ .Values.dbpassword | toString | b64enc}}
    {{ end }} */}}
    {{ end }}
type: Opaque