{{- $pgsecretname := printf "%s.%s.%s" .Values.db.dbUser .Values.clusterSvcName .Values.db.secretPostfix -}}
{{- $pgsecret := (lookup "v1" "Secret" .Release.Namespace $pgsecretname) -}}
{{/*{{- $secret := (lookup "v1" "Secret" .Release.Namespace "keycloak-db-secret") -}} */}}
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: {{ .Release.Namespace }}
    labels:
        velero-backup: "true"
stringData:
    # Required for AWS Backup functionality
    POSTGRES_SUPERUSER: {{ quote .Values.keycloak_db.stringData.POSTGRES_SUPERUSER }}
    POSTGRES_USERNAME: {{ quote .Values.keycloak_db.stringData.POSTGRES_USERNAME }}
data:
    {{ if $pgsecret }}
    POSTGRES_PASSWORD: {{ $pgsecret.data.password }}
    {{ else }}
    POSTGRES_PASSWORD: {{ .Values.dbpassword | toString | b64enc}}
    {{ end }}
type: Opaque