{{- $pgsecret := (lookup "v1" "Secret" .Release.Namespace "keycloak-client-secret-mqtt-broker") -}}
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-client-secret-mqtt-broker
    namespace: {{ .Release.Namespace }}
{{ if $pgsecret }}
stringData:
    CLIENT_ID: {{ $pgsecret.data.CLIENT_ID }}
data:
    CLIENT_SECRET: {{ $pgsecret.data.CLIENT_SECRET }}
{{ else }}
stringData:
    CLIENT_ID: {{ .Values.keycloak.oisp.mqttBroker.client }}
data:
    CLIENT_SECRET: {{ .Values.keycloak.oisp.mqttBroker.clientSecret | toString | b64enc }}
{{ end }}
type: Opaque