{{- $pgsecret := (lookup "v1" "Secret" .Release.Namespace "keycloak-client-secret-ngsild-updates") -}}
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-client-secret-ngsild-updates
    namespace: {{ .Release.Namespace }}
{{ if $pgsecret }}
stringData:
    CLIENT_ID: {{ $pgsecret.data.CLIENT_ID }}
data:
    CLIENT_SECRET: {{ $pgsecret.data.CLIENT_SECRET }}
{{ else }}
stringData:
    CLIENT_ID: {{ .Values.keycloak.ngsildUpdates.client }}
data:
    CLIENT_SECRET: {{ .Values.keycloak.ngsildUpdates.clientSecret | toString | b64enc }}
{{ end }}
type: Opaque