{{- $pgsecret := (lookup "v1" "Secret" .Release.Namespace "credential-iff-realm-user-iff") -}}
apiVersion: v1
kind: Secret
metadata:
    name: credential-iff-realm-user-iff
    namespace: {{ .Release.Namespace }}
{{ if $pgsecret }}
stringData:
    username: {{ $pgsecret.data.username }}
data:
    password: {{ $pgsecret.data.password }}
{{ else }}
stringData:
    username: {{ .Values.keycloak.realmTestUser.username }}
data:
    password: {{ .Values.keycloak.realmTestUser.password | toString | b64enc }}
{{ end }}
type: Opaque