{{- $secret := (lookup "v1" "Secret" .Release.Namespace "credential-iff-realm-user-iff") -}}
apiVersion: v1
kind: Secret
metadata:
    name: credential-iff-realm-user-iff
    namespace: {{ .Release.Namespace }}
    labels:
        velero-backup: "true"
{{ if $secret }}
data:
    username: {{ $secret.data.username }}
    password: {{ $secret.data.password }}
{{ else }}
data:
    username: {{ .Values.keycloak.realmTestUser.username | toString | b64enc }}
    password: {{ .Values.keycloak.realmTestUser.password | toString | b64enc }}
{{ end }}
type: Opaque