apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: iff-minio-tenant
  namespace: {{ .Release.Namespace }}
spec:
  env:
  - name: "MINIO_STORAGE_CLASS_STANDARD"
    value: "EC:2"
  - name: "MINIO_BROWSER"
    value: "on"
  requestAutoCert: false
  configuration:
    name: iff-minio-tenant-configuration
  users:
    - name: minio-user
  pools:
    - servers: 1
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.minio.storageSize }}
