{{- $secret := (lookup "v1" "Secret" .Release.Namespace "iff-creds-secret") -}}
apiVersion: v1
data:
  accesskey: {{ .Values.minio.adminAccessKey | toString | b64enc }}
  {{- if $secret }}
  secretkey: {{ $secret.data.secretkey }}
  {{- else }}
  secretkey: {{ .Values.minioAdminSecretKey | toString | b64enc }}
  {{- end }}

kind: Secret
metadata:
  name: iff-creds-secret
  namespace: {{ .Release.Namespace }}
type: Opaque