apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alerta.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "alerta.name" . }}
    chart: {{ include "alerta.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "alerta.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "alerta.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.externalRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OAUTH2_CLIENT_SECRET
              valueFrom: 
                secretKeyRef:
                  name: keycloak-client-secret-alerta-ui
                  key: CLIENT_SECRET
            - name: OAUTH2_CLIENT_ID
              value: {{ .Values.keycloak.alerta.client }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: alerta-db-secret
                  key: DATABASE_URL
            - name: KEYCLOAK_URL
              value: {{ .Values.keycloak.externalAuthService.protocol }}//{{ .Values.keycloak.externalAuthService.domainname }}
            - name: KEYCLOAK_REALM
              value: {{ .Values.keycloak.alerta.realm }}
            - name: ADMIN_USERS
              value: {{ list .Values.alerta.adminUser | join "," }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alerta
                  key: alerta-admin-password
            - name: ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: alerta
                  key: alerta-admin-key
            - name: ALERTA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alerta
                  key: alerta-admin-key
              {{- if .Values.alertaInstallPlugins }}
            - name: INSTALL_PLUGINS
              value: {{ .Values.alertaInstallPlugins | join "," }}
              {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 300
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
          volumeMounts:
          {{- range .Values.extraSecretMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
            - name: alerta-config
              mountPath: /app/alertad.conf
              subPath: alertad.conf
              {{- if .Values.alertaWebUIConfig }}
            - name: alerta-config
              mountPath: /app/config.js
              subPath: config.js
              {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: alerta-config
          configMap:
            name: {{ include "alerta.fullname" . }}
      {{- range .Values.extraSecretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
