{{- $pgsecret := (lookup "v1" "Secret" .Release.Namespace "alerta") -}}
apiVersion: v1
kind: Secret
metadata:
  name: alerta
  namespace: {{ .Release.Namespace }}
  labels:
    app: alerta
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if $pgsecret }}
  alerta-admin-password: {{ index $pgsecret "data" "alerta-admin-password" }}
  alerta-admin-key: {{ index $pgsecret "data" "alerta-admin-key" }}
  {{ else }}
  alerta-admin-key: {{ .Values.alerta.adminKey | b64enc | quote }}
  alerta-admin-password: {{ .Values.alerta.adminPassword | b64enc | quote }}
  {{ end }}