apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fuseki-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.fuseki.storage.size }}
