{{- if not .Values.aaio.enabled }}
{{- if .Values.ConfigServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.ConfigServer.name }}
  name: {{ .Values.ConfigServer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.ConfigServer.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.ConfigServer.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: {{ .Values.ConfigServer.name }}
    spec:
      containers:
      - image: {{ .Values.mainRepo }}/digitaltwin:config-server_{{ .Values.scorpio.tag }}
        command: ["java"]
        args: ["-XshowSettings:vm", {{ .Values.scorpio.heap_min.Xms | quote }}, {{ .Values.scorpio.heap_min.Xmx | quote }}, "-jar", "config-server.jar"]
        env:
        {{- if .Values.springArgs.overrideSpringArgs }}
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end}}
        imagePullPolicy: {{ .Values.ConfigServer.image.pullPolicy }}
        name: {{ .Values.ConfigServer.name }}
        ports:
        - containerPort: 8888
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://eureka:8761/eureka/apps/CONFIGSERVER/$HOSTNAME:configserver:8888/status?value=OUT_OF_SERVICE"
        {{- if .Values.ConfigServer.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:8888/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.ConfigServer.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.ConfigServer.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.ConfigServer.readinessProbe.periodSeconds }}
          {{- end}}
        resources:
{{ toYaml .Values.scorpio.resources_min | indent 10 }}
      restartPolicy: {{ .Values.ConfigServer.restartPolicy }}
      {{- if .Values.ConfigServer.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.ConfigServer.serviceAccount.name }}
      {{- end}}
      {{- if .Values.ConfigServer.securityContext.enabled }}
      securityContext:
{{ toYaml .Values.ConfigServer.securityContext.settings | indent 8 }}
      {{- end}}
      terminationGracePeriodSeconds: {{ .Values.ConfigServer.terminationGracePeriodSeconds }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
status: {}
{{- end }}
{{- end }}