{{- if not .Values.aaio.enabled }}
{{- if .Values.EntityManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.EntityManager.name }}
  name: {{ .Values.EntityManager.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.EntityManager.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.EntityManager.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: {{ .Values.EntityManager.name }}
    spec:
      containers:
      - image: {{ .Values.mainRepo }}/digitaltwin:EntityManager_{{ .Values.scorpio.tag }}
        command: ["java"]
        args: ["-XshowSettings:vm", {{ .Values.scorpio.heap_main.Xms | quote }}, {{ .Values.scorpio.heap_main.Xmx | quote }}, "-jar", "EntityManager.jar"]
        env:
          - name: CLIENT_ID
            value: {{ .Values.keycloak.scorpio.client }}
          - name: REALM
            value: {{ .Values.keycloak.scorpio.realm }}
        {{- range $key, $val := .Values.postgres_vars}}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
          - name: KEYCLOAK_SERVER_URL
            value: {{ .Values.keycloak.externalAuthService.protocol }}//{{ .Values.keycloak.externalAuthService.domainname }}{{.Values.keycloak.externalAuthService.path }}
          - name: POSTGRES_SERVICE
            value: {{ .Values.clusterSvcName }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.dbUser -}}.{{- .Values.clusterSvcName -}}.{{- .Values.db.secretPostfix }}
                key: password
        {{- range $key, $val := .Values.keycloak_vars}}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        {{- range $key, $val := .Values.kafka_vars }}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        {{- if .Values.springArgs.overrideSpringArgs }}
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end}}
        imagePullPolicy: {{ .Values.EntityManager.image.pullPolicy }}
        name: {{ .Values.EntityManager.name }}
        ports:
        - containerPort: 1025
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://eureka:8761/eureka/apps/ENTITY-MANAGER/$HOSTNAME:entity-manager:1025/status?value=OUT_OF_SERVICE"
        {{- if .Values.EntityManager.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:1025/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.EntityManager.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.EntityManager.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.EntityManager.readinessProbe.periodSeconds }}
          {{- end}}
        resources:
{{ toYaml .Values.scorpio.resources_main | indent 10 }}
      restartPolicy: {{ .Values.EntityManager.restartPolicy }}
      {{- if .Values.EntityManager.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.EntityManager.serviceAccount.name }}
      {{- end}}
      {{- if .Values.EntityManager.securityContext.enabled }}
      securityContext:
{{ toYaml .Values.EntityManager.securityContext.settings | indent 8 }}
      {{- end}}
      terminationGracePeriodSeconds: {{ .Values.EntityManager.terminationGracePeriodSeconds }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
status: {}
{{- end }}
{{- end }}