---
{{- if and (ne .Values.ingressType "traefik") (ne .Values.ingressType "nginx") }}
{{- fail "ingressType must either be \"traefik\" or \"nginx\"" }}
{{- end }}
{{- if not (regexMatch "/$" .Values.scorpio.externalPath) }}
{{- fail "scorpio.externalPath does not end with /" }}
{{- end}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scorpio-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressType | quote }}
    {{- if and (ne .Values.scorpio.externalPath "/") (eq .Values.ingressType "traefik") }}
    traefik.ingress.kubernetes.io/router.middlewares: iff-remove-path-scorpio@kubernetescrd
    {{- else }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- end }}
    cert-manager.io/cluster-issuer: {{ .Values.certmanager.issuer }}

  namespace: {{ .Release.Namespace }}
spec:
  tls:
  - hosts:
    - {{ .Values.scorpio.externalHostname }}
    secretName: {{ .Values.certmanager.secret }}-scorpio
  rules:
  - host: {{ .Values.scorpio.externalHostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.scorpio.internalHostname }}
            port:
              number: {{ .Values.scorpio.internalPort }}
        {{- if (eq .Values.ingressType "nginx") }}
        path: {{ .Values.scorpio.externalPath }}(.*)
        {{- else }}
        path: {{ .Values.scorpio.externalPath }}
        {{- end }}
        pathType: ImplementationSpecific
---
{{- if and (ne .Values.scorpio.externalPath "/") (eq .Values.ingressType "traefik") }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: remove-path-scorpio
spec:
  replacePathRegex:
    regex: ^{{ .Values.scorpio.externalPath }}(.*)
    replacement: /$1
{{- end }}