apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scorpio-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressType | quote }}
    #ingress.kubernetes.io/force-ssl-redirect: "true"
    #ingress.kubernetes.io/ssl-redirect: "true"
  namespace: {{ .Release.Namespace }}
spec:
  tls:
  - hosts:
    - {{ .Values.scorpio.externalHostname }}
    secretName: {{ .Values.certmanager.secret }}
  rules:
  - host: {{ .Values.scorpio.externalHostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.scorpio.internalHostname }}
            port:
              number: {{ .Values.scorpio.internalPort }}
        path: /
        pathType: ImplementationSpecific