{{- if .Values.aaio.enabled }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafka_topic_vars.ENTITY_TOPIC}}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{.Values.kafka_topic_vars.retention}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafka_topic_vars.REGISTRY_TOPIC}}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{.Values.kafka_topic_vars.retention}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafka_topic_vars.TEMPORAL_TOPIC}}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{.Values.kafka_topic_vars.retention}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafka_topic_vars.INTERNAL_NOTIFY_TOPIC}}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{.Values.kafka_topic_vars.retention}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafka_topic_vars.INTERNAL_REGISTRYSUB_TOPIC}}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{.Values.kafka_topic_vars.retention}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafka_topic_vars.SUB_ALIVE_TOPIC}}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{.Values.kafka_topic_vars.retention}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafka_topic_vars.SUB_SYNC_TOPIC}}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{.Values.kafka_topic_vars.retention}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafka_topic_vars.REGISTRYSUB_SYNC_TOPIC}}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{.Values.kafka_topic_vars.retention}}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{.Values.kafka_topic_vars.REGISTRYSUB_ALIVE_TOPIC}}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: {{.Values.kafka_topic_vars.retention}}
{{- end }}