{{- if .Values.aaio.enabled }}
{{- $name := printf "%s.%s.%s" .Values.db.dbUser .Values.clusterSvcName .Values.db.secretPostfix }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $name) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.aaio.name }}
  labels:
    service: {{ .Values.aaio.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.aaio.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.aaio.name }}
  template:
    metadata:
      labels:
        service: {{ .Values.aaio.name }}
      annotations:
        {{- if $secret }}
        checksum/credentials: {{ printf "%s" $secret | toString | sha256sum }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.aaio.name }}
          image: {{ .Values.mainRegistry }}/{{ .Values.mainRepo }}/{{ .Values.aaio.name }}:{{ .Values.mainVersion }}
          imagePullPolicy: {{ .Values.aaio.image.pullPolicy }}
          env:
            - name: CLIENT_ID
              value: {{ .Values.keycloak.scorpio.client }}
            - name: REALM
              value: {{ .Values.keycloak.scorpio.realm }}
          {{- range $key, $val := .Values.postgres_vars}}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
            - name: KEYCLOAK_SERVER_URL
              value: {{ .Values.keycloak.externalAuthService.protocol }}//{{ .Values.keycloak.externalAuthService.domainname }}{{.Values.keycloak.externalAuthService.path }}
            - name: POSTGRES_SERVICE
              value: {{ .Values.clusterSvcName }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.dbUser -}}.{{- .Values.clusterSvcName -}}.{{- .Values.db.secretPostfix }}
                  key: password
            - name: POSTGRES_DBNAME
              value: {{ .Values.db.scorpioDb }}
          {{- range $key, $val := .Values.keycloak_vars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- range $key, $val := .Values.kafka_vars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- range $key, $val := .Values.kafka_topic_vars }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          ports:
            - containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.aaio.resources | nindent 12 }}
{{- end }}