{{- if .Values.SubscriptionManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.SubscriptionManager.name }}
  name: {{ .Values.SubscriptionManager.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.SubscriptionManager.replicas }}
  selector:
    matchLabels:
      service: {{ .Values.SubscriptionManager.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: {{ .Values.SubscriptionManager.name }}
    spec:
      containers:
      - image: {{ .Values.mainRepo }}/digitaltwin:SubscriptionManager_{{ .Values.scorpio.tag }}
        env:
          - name: CLIENT_ID
            value: {{ .Values.keycloak.scorpio.client }}
          - name: REALM
            value: {{ .Values.keycloak.scorpio.realm }}
        {{- range $key, $val := .Values.postgres_vars}}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
          - name: KEYCLOAK_SERVER_URL
            value: {{ .Values.keycloak.externalAuthService.protocol }}//{{ .Values.keycloak.externalAuthService.domainname }}{{.Values.keycloak.externalAuthService.path }}
          - name: POSTGRES_SERVICE
            value: {{ .Values.clusterSvcName }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.dbUser -}}.{{- .Values.clusterSvcName -}}.{{- .Values.db.secretPostfix }}
                key: password
        {{- range $key, $val := .Values.keycloak_vars}}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        {{- range $key, $val := .Values.kafka_vars }}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        {{- if .Values.springArgs.overrideSpringArgs }}
        env:
          - name: spring_args
            value: {{ .Values.springArgs.value }}
        {{- end}}
        imagePullPolicy: {{ .Values.SubscriptionManager.image.pullPolicy }}
        name: {{ .Values.SubscriptionManager.name }}
        ports:
        - containerPort: 2025
          protocol: TCP
        lifecycle:
           preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -X PUT "http://eureka:8761/eureka/apps/SUBSCRIPTION-MANAGER/$HOSTNAME:subscription-manager:2025/status?value=OUT_OF_SERVICE"
        {{- if .Values.SubscriptionManager.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:2025/actuator/health | grep --quiet -e
              '^{\"status\"\:\"UP\".*}$'
          failureThreshold: {{ .Values.SubscriptionManager.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.SubscriptionManager.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.SubscriptionManager.readinessProbe.periodSeconds }}
          {{- end}}
        resources:
{{ toYaml .Values.SubscriptionManager.resources | indent 10 }}
      restartPolicy: {{ .Values.SubscriptionManager.restartPolicy }}
      {{- if .Values.SubscriptionManager.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.SubscriptionManager.serviceAccount.name }}
      {{- end}}
      {{- if .Values.SubscriptionManager.securityContext.enabled }}
      securityContext:
{{ toYaml .Values.SubscriptionManager.securityContext.settings | indent 8 }}
      {{- end}}
      terminationGracePeriodSeconds: {{ .Values.SubscriptionManager.terminationGracePeriodSeconds }}
      imagePullSecrets:
        - name: {{ .Values.imageCredentials.name }}
status: {}
{{- end }}