apiVersion: v1
kind: Service
metadata:
  name: mqtt-bridge
  namespace: {{ .Release.Namespace }}
  labels:
    app: mqtt-bridge
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mqtt.bridge.port }}
      protocol: TCP
      name: http
  selector:
    app: mqtt-bridge