---
apiVersion: industry-fusion.com/v1alpha2
kind: BeamSqlTable
metadata:
  name: ngsild-updates
spec:
  name: ngsild_updates
  connector: kafka
  fields:
    - 'op': STRING
    - 'overwriteOrReplace': Boolean
    - 'entities': STRING
  kafka:
    topic: {{.Values.kafkaBridge.ngsildUpdates.listenTopic}}
    properties:
      bootstrap.servers: {{.Values.kafka.bootstrapServer}}
    scan.startup.mode: latest-offset
  value:
    format: json
    json.fail-on-missing-field: false
    json.ignore-parse-errors: true
