spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BROKERS}:${KAFKA_PORT}
    consumer:
      topic: ${SCORPIO_ENTITY_DB_TOPIC}
      bootstrap-servers: ${KAFKA_BROKERS}:${KAFKA_PORT}
      group-id: ${CONSUMER_GROUP_ID}