name: Nigthly
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  call-build:
    uses: IndustryFusion/DigitalTwin/.github/workflows/build.yaml@main
  call-test:
    uses: IndustryFusion/DigitalTwin/.github/workflows/k8s-tests.yaml@main
